/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/airplane-transformed.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Cube_2_2_Body_0_1.geometry} material={materials.Body} />
        <mesh geometry={nodes.Cube_2_2_Body_0_2.geometry} material={materials.material} />
        <mesh geometry={nodes.Cube_2_2_Body_0_3.geometry} material={materials.Glass} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/airplane-transformed.glb')
