/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: marcos.driguez (https://sketchfab.com/marcos.driguez)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/skateboard-free-model-5fb8302331154d0b80e7aa9352a3b664
title: SkateBoard Free Model
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('models/skateboard/model.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-0.44, 53.71, -0.03]} rotation={[-1.58, 0, -Math.PI / 2]} scale={100}>
            {/* Board */}
            <mesh castShadow geometry={nodes.Plane005_SKATE_TEXTURE_0.geometry} material={materials.SKATE_TEXTURE} />
          </group>
          <group position={[-0.3, 49.02, 119.11]} rotation={[1.6, 0, -Math.PI / 2]} scale={18.06}>
            <mesh castShadow receiveShadow geometry={nodes.Cube001_SKATE_TEXTURE_0.geometry} material={materials.SKATE_TEXTURE} />
          </group>
          <group position={[-0.3, 49.02, 119.11]} rotation={[1.6, 0, -Math.PI / 2]} scale={18.06}>
            <mesh castShadow receiveShadow geometry={nodes.Cube002_SKATE_TEXTURE_0.geometry} material={materials.SKATE_TEXTURE} />
          </group>
          <group position={[-0.3, 35.93, 114.35]} rotation={[1.3, 0, -1.57]} scale={29.98}>
            <mesh castShadow receiveShadow geometry={nodes.Cube003_SKATE_TEXTURE_0.geometry} material={materials.SKATE_TEXTURE} />
          </group>
          <group position={[-0.3, 31.71, 115.55]} rotation={[1.3, 0, -Math.PI / 2]} scale={29.51}>
            <mesh castShadow receiveShadow geometry={nodes.Cube004_SKATE_TEXTURE_0.geometry} material={materials.SKATE_TEXTURE} />
          </group>
          <group position={[-0.3, 21.93, 118.28]} rotation={[1.29, 0, -1.57]} scale={29.51}>
            <mesh castShadow receiveShadow geometry={nodes.Cube005_SKATE_TEXTURE_0.geometry} material={materials.SKATE_TEXTURE} />
          </group>
          <group position={[-0.2, 48.35, -118.29]} rotation={[1.58, 0, Math.PI / 2]} scale={18.06}>
            <mesh castShadow receiveShadow geometry={nodes.Cube012_SKATE_TEXTURE_0.geometry} material={materials.SKATE_TEXTURE} />
          </group>
          <group position={[-0.2, 48.35, -118.29]} rotation={[1.58, 0, Math.PI / 2]} scale={18.06}>
            <mesh castShadow receiveShadow geometry={nodes.Cube013_SKATE_TEXTURE_0.geometry} material={materials.SKATE_TEXTURE} />
          </group>
          <group position={[-0.2, 34.89, -114.22]} rotation={[1.89, 0, Math.PI / 2]} scale={29.98}>
            <mesh castShadow receiveShadow geometry={nodes.Cube014_SKATE_TEXTURE_0.geometry} material={materials.SKATE_TEXTURE} />
          </group>
          <group position={[-0.2, 30.29, -115.72]} rotation={[1.89, 0, Math.PI / 2]} scale={29.51}>
            <mesh castShadow receiveShadow geometry={nodes.Cube015_SKATE_TEXTURE_0.geometry} material={materials.SKATE_TEXTURE} />
          </group>
          <group position={[-0.2, 21.64, -118.27]} rotation={[1.9, 0, Math.PI / 2]} scale={29.51}>
            <mesh castShadow receiveShadow geometry={nodes.Cube016_SKATE_TEXTURE_0.geometry} material={materials.SKATE_TEXTURE} />
          </group>
          <group position={[-0.3, 34.67, -137.34]} rotation={[1.58, 0, -Math.PI]} scale={69.25}>
            <mesh castShadow receiveShadow geometry={nodes.Cylinder004_SKATE_TEXTURE_0.geometry} material={materials.SKATE_TEXTURE} />
          </group>
          <group position={[12.12, 41.65, 137.75]} rotation={[-1.58, 0, -Math.PI / 2]} scale={122.27}>
            <mesh castShadow receiveShadow geometry={nodes.Cube017_SKATE_TEXTURE_0.geometry} material={materials.SKATE_TEXTURE} />
          </group>
          <group position={[-13.05, 41.65, 137.75]} rotation={[-1.58, 0, -Math.PI / 2]} scale={122.27}>
            <mesh castShadow receiveShadow geometry={nodes.Cube019_SKATE_TEXTURE_0.geometry} material={materials.SKATE_TEXTURE} />
          </group>
          <group position={[12.12, 42.4, 106.78]} rotation={[-1.58, 0, -Math.PI / 2]} scale={122.27}>
            <mesh castShadow receiveShadow geometry={nodes.Cube020_SKATE_TEXTURE_0.geometry} material={materials.SKATE_TEXTURE} />
          </group>
          <group position={[-13.05, 42.4, 106.78]} rotation={[-1.58, 0, -Math.PI / 2]} scale={122.27}>
            <mesh castShadow receiveShadow geometry={nodes.Cube021_SKATE_TEXTURE_0.geometry} material={materials.SKATE_TEXTURE} />
          </group>
          <group position={[12.12, 41.26, -107.18]} rotation={[-1.58, 0, -Math.PI / 2]} scale={122.27}>
            <mesh castShadow receiveShadow geometry={nodes.Cube022_SKATE_TEXTURE_0.geometry} material={materials.SKATE_TEXTURE} />
          </group>
          <group position={[-13.05, 41.26, -107.18]} rotation={[-1.58, 0, -Math.PI / 2]} scale={122.27}>
            <mesh castShadow receiveShadow geometry={nodes.Cube023_SKATE_TEXTURE_0.geometry} material={materials.SKATE_TEXTURE} />
          </group>
          <group position={[12.12, 41.96, -138.14]} rotation={[-1.58, 0, -Math.PI / 2]} scale={122.27}>
            <mesh castShadow receiveShadow geometry={nodes.Cube024_SKATE_TEXTURE_0.geometry} material={materials.SKATE_TEXTURE} />
          </group>
          <group position={[-13.05, 41.96, -138.14]} rotation={[-1.58, 0, -Math.PI / 2]} scale={122.27}>
            <mesh castShadow receiveShadow geometry={nodes.Cube025_SKATE_TEXTURE_0.geometry} material={materials.SKATE_TEXTURE} />
          </group>
          <group position={[-52.78, 17.76, 135.49]} rotation={[-0.01, -Math.PI / 2, 0]} scale={[17.52, 17.52, 14.67]}>
            <mesh castShadow receiveShadow geometry={nodes.Circle001_SKATE_TEXTURE_0.geometry} material={materials.SKATE_TEXTURE} />
          </group>
          <group position={[-39.17, 17.76, 135.49]} rotation={[-0.01, -Math.PI / 2, 0]} scale={[17.52, 17.52, 14.67]}>
            <mesh castShadow receiveShadow geometry={nodes.Circle003_SKATE_TEXTURE_0.geometry} material={materials.SKATE_TEXTURE} />
          </group>
          <group position={[-55.03, 17.68, 135.46]} rotation={[0, -Math.PI / 2, 0]} scale={104.72}>
            <mesh castShadow receiveShadow geometry={nodes.Cube026_SKATE_TEXTURE_0.geometry} material={materials.SKATE_TEXTURE} />
          </group>
          <group position={[-45.94, 17.76, -135.91]} rotation={[-0.01, -Math.PI / 2, 0]} scale={17.76}>
            <mesh castShadow receiveShadow geometry={nodes.Circle004_SKATE_TEXTURE_0.geometry} material={materials.SKATE_TEXTURE} />
          </group>
          <group position={[-52.78, 17.76, -135.91]} rotation={[-0.01, -Math.PI / 2, 0]} scale={[17.52, 17.52, 14.67]}>
            <mesh castShadow receiveShadow geometry={nodes.Circle005_SKATE_TEXTURE_0.geometry} material={materials.SKATE_TEXTURE} />
          </group>
          <group position={[-39.17, 17.76, -135.91]} rotation={[-0.01, -Math.PI / 2, 0]} scale={[17.52, 17.52, 14.67]}>
            <mesh castShadow receiveShadow geometry={nodes.Circle006_SKATE_TEXTURE_0.geometry} material={materials.SKATE_TEXTURE} />
          </group>
          <group position={[-55.2, 17.68, -135.94]} rotation={[0, -Math.PI / 2, 0]} scale={104.72}>
            <mesh castShadow receiveShadow geometry={nodes.Cube028_SKATE_TEXTURE_0.geometry} material={materials.SKATE_TEXTURE} />
          </group>
          <group position={[52.26, 17.68, 135.49]} rotation={[-3.13, 1.57, 0]} scale={[17.52, 17.52, 14.67]}>
            <mesh castShadow receiveShadow geometry={nodes.Circle007_SKATE_TEXTURE_0.geometry} material={materials.SKATE_TEXTURE} />
          </group>
          <group position={[38.65, 17.68, 135.49]} rotation={[-3.13, 1.57, 0]} scale={[17.52, 17.52, 14.67]}>
            <mesh castShadow receiveShadow geometry={nodes.Circle009_SKATE_TEXTURE_0.geometry} material={materials.SKATE_TEXTURE} />
          </group>
          <group position={[54.64, 17.76, 135.46]} rotation={[-Math.PI, Math.PI / 2, 0]} scale={104.72}>
            <mesh castShadow receiveShadow geometry={nodes.Cube029_SKATE_TEXTURE_0.geometry} material={materials.SKATE_TEXTURE} />
          </group>
          <group position={[52.26, 17.68, -135.91]} rotation={[-3.13, 1.57, 0]} scale={[17.52, 17.52, 14.67]}>
            <mesh castShadow receiveShadow geometry={nodes.Circle010_SKATE_TEXTURE_0.geometry} material={materials.SKATE_TEXTURE} />
          </group>
          <group position={[38.65, 17.68, -135.91]} rotation={[-3.13, 1.57, 0]} scale={[17.52, 17.52, 14.67]}>
            <mesh castShadow receiveShadow geometry={nodes.Circle012_SKATE_TEXTURE_0.geometry} material={materials.SKATE_TEXTURE} />
          </group>
          <group position={[54.59, 17.76, -135.94]} rotation={[-Math.PI, Math.PI / 2, 0]} scale={104.72}>
            <mesh castShadow receiveShadow geometry={nodes.Cube030_SKATE_TEXTURE_0.geometry} material={materials.SKATE_TEXTURE} />
          </group>
          <group position={[-13.05, 47.23, 137.82]} rotation={[1.59, 0, Math.PI / 2]} scale={90.61}>
            <mesh castShadow receiveShadow geometry={nodes.Cube031_SKATE_TEXTURE_0.geometry} material={materials.SKATE_TEXTURE} />
          </group>
          <group position={[12.14, 47.23, 137.82]} rotation={[1.59, 0, Math.PI / 2]} scale={90.61}>
            <mesh castShadow receiveShadow geometry={nodes.Cube032_SKATE_TEXTURE_0.geometry} material={materials.SKATE_TEXTURE} />
          </group>
          <group position={[-13.05, 48.19, 106.97]} rotation={[1.59, 0, Math.PI / 2]} scale={90.61}>
            <mesh castShadow receiveShadow geometry={nodes.Cube033_SKATE_TEXTURE_0.geometry} material={materials.SKATE_TEXTURE} />
          </group>
          <group position={[12.14, 48.19, 106.97]} rotation={[1.59, 0, Math.PI / 2]} scale={90.61}>
            <mesh castShadow receiveShadow geometry={nodes.Cube034_SKATE_TEXTURE_0.geometry} material={materials.SKATE_TEXTURE} />
          </group>
          <group position={[-13.05, 47.07, -107.1]} rotation={[1.58, 0, Math.PI / 2]} scale={90.61}>
            <mesh castShadow receiveShadow geometry={nodes.Cube035_SKATE_TEXTURE_0.geometry} material={materials.SKATE_TEXTURE} />
          </group>
          <group position={[12.14, 47.07, -107.1]} rotation={[1.58, 0, Math.PI / 2]} scale={90.61}>
            <mesh castShadow receiveShadow geometry={nodes.Cube036_SKATE_TEXTURE_0.geometry} material={materials.SKATE_TEXTURE} />
          </group>
          <group position={[-13.05, 47.51, -138.12]} rotation={[1.58, 0, Math.PI / 2]} scale={90.61}>
            <mesh castShadow receiveShadow geometry={nodes.Cube037_SKATE_TEXTURE_0.geometry} material={materials.SKATE_TEXTURE} />
          </group>
          <group position={[12.14, 47.51, -138.12]} rotation={[1.58, 0, Math.PI / 2]} scale={90.61}>
            <mesh castShadow receiveShadow geometry={nodes.Cube038_SKATE_TEXTURE_0.geometry} material={materials.SKATE_TEXTURE} />
          </group>
          <group position={[-0.41, 17.93, 119.52]} rotation={[1.3, 0, Math.PI / 2]} scale={127.06}>
            <mesh castShadow receiveShadow geometry={nodes.Cube039_SKATE_TEXTURE_0.geometry} material={materials.SKATE_TEXTURE} />
          </group>
          <group position={[-0.19, 17.32, -119.99]} rotation={[1.89, 0, Math.PI / 2]} scale={127.06}>
            <mesh castShadow receiveShadow geometry={nodes.Cube040_SKATE_TEXTURE_0.geometry} material={materials.SKATE_TEXTURE} />
          </group>
          <group position={[-0.66, 40.09, 113.59]} rotation={[-1.84, 0, -Math.PI / 2]} scale={154.97}>
            <mesh castShadow receiveShadow geometry={nodes.Cube041_SKATE_TEXTURE_0.geometry} material={materials.SKATE_TEXTURE} />
          </group>
          <group position={[-0.66, 39.13, -113]} rotation={[-1.25, -0.03, 1.49]} scale={154.97}>
            <mesh castShadow receiveShadow geometry={nodes.Cube042_SKATE_TEXTURE_0.geometry} material={materials.SKATE_TEXTURE} />
          </group>
          <group position={[-0.31, 18.71, 119.29]} rotation={[-1.85, 0, -Math.PI / 2]} scale={22.03}>
            <mesh castShadow receiveShadow geometry={nodes.Cube043_SKATE_TEXTURE_0.geometry} material={materials.SKATE_TEXTURE} />
          </group>
          <group position={[-0.31, 18.01, -119.61]} rotation={[-1.23, 0, -Math.PI / 2]} scale={22.03}>
            <mesh castShadow receiveShadow geometry={nodes.Cube080_SKATE_TEXTURE_0.geometry} material={materials.SKATE_TEXTURE} />
          </group>
          <group position={[-45.94, 17.76, 135.38]} rotation={[-0.01, -Math.PI / 2, 0]} scale={17.76}>
            <mesh castShadow receiveShadow geometry={nodes.Circle013_SKATE_TEXTURE_0.geometry} material={materials.SKATE_TEXTURE} />
          </group>
          <group position={[-0.3, 34.44, 137.78]} rotation={[1.61, 0, 0]} scale={69.25}>
            <mesh castShadow receiveShadow geometry={nodes.Cylinder002_SKATE_TEXTURE_0.geometry} material={materials.SKATE_TEXTURE} />
            <mesh castShadow receiveShadow geometry={nodes.Cylinder002_SKATE_TEXTURE_0_1.geometry} material={materials.SKATE_TEXTURE} />
            <mesh castShadow receiveShadow geometry={nodes.Cylinder002_SKATE_TEXTURE_0_2.geometry} material={materials.SKATE_TEXTURE} />
            <mesh castShadow receiveShadow geometry={nodes.Cylinder002_SKATE_TEXTURE_0_3.geometry} material={materials.SKATE_TEXTURE} />
            <mesh castShadow receiveShadow geometry={nodes.Cylinder002_SKATE_TEXTURE_0_4.geometry} material={materials.SKATE_TEXTURE} />
            <mesh castShadow receiveShadow geometry={nodes.Cylinder002_SKATE_TEXTURE_0_5.geometry} material={materials.SKATE_TEXTURE} />
            <mesh castShadow receiveShadow geometry={nodes.Cylinder002_SKATE_TEXTURE_0_6.geometry} material={materials.SKATE_TEXTURE} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('models/skateboard/model.glb')
